variables:
  # Docker in Docker
  DOCKER_HOST: tcp://docker:2376/
  DOCKER_TLS_VERIFY: '1'
  DOCKER_TLS_CERTDIR: '/certs'
  DOCKER_CERT_PATH: '/certs/client'

stages:
  - build

services:
  - name: docker:dind
    command:
      [
        '/bin/sh',
        '-c',
        '(update-ca-certificates && dockerd-entrypoint.sh || exit )',
      ]

.dind_self_signed_cert:
  before_script:
    - update-ca-certificates
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    # Wait for docker to be up
    - while ! docker info; do sleep 1; done

build:
  image: docker:cli
  stage: build
  extends: .dind_self_signed_cert
  script:
    - docker build -t $CI_REGISTRY_IMAGE:$CI_COMMIT_TAG .
    - docker push $CI_REGISTRY_IMAGE:$CI_COMMIT_TAG
  rules:
    - if: $CI_COMMIT_TAG
  tags:
    - k8s
